imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @MesdPresentationBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

#Jasper Report Bundle Configuration
mesd_jasper_report:
    options_handler: mesd_report_demo.handler.report_options
    connection:
        host: %report_host%
        port: %report_port%
        username: %report_user%
        password: %report_pass%
    folder_cache:
        use_cache: true
        cache_dir: ../app/cache/resource_cache/
        cache_timeout: 30
    report_cache:
        use_cache: true
        cache_dir: ../app/cache/report_cache

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_name:          %app_name%
        app_abbreviation:  %app_abbreviation%
        app_description:   %app_description%
        app_keywords:      %app_keywords%
        app_url:           %app_url%
        app_version:       %app_version%
        app_build:         %app_build%
        app_release:       %app_release%
        app_license_1:     %app_license_1%
        app_license_url_1: %app_license_url_1%
        app_license_2:     %app_license_2%
        app_license_url_2: %app_license_url_2%
        org_name:          %org_name%
        org_abbreviation:  %org_abbreviation%
        org_address:       %org_address%
        org_telephone:     %org_telephone%
        org_email:         %org_email%
        org_url:           %org_url%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - MesdPresentationBundle
    filters:
        cssrewrite: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/filters/cssembed-0.4.5.jar"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less:
            node:       %node_base_path%
            node_paths: [%node_modules_path%]
            apply_to:   "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: dev
        connections:
            prod:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            dev:
                driver:   "%dev_database_driver%"
                host:     "%dev_database_host%"
                port:     "%dev_database_port%"
                dbname:   "%dev_database_name%"
                user:     "%dev_database_user%"
                password: "%dev_database_password%"
                charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
