parameters:
#    mesd_breadcrumb.example.class: Mesd\BreadcrumbBundle\Example

services:
#    Mesd_breadcrumb.example:
#        class: %mesd_breadcrumb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
