MesdReportDemoBundle_default:
    resource: "@MesdReportDemoBundle/Resources/config/routing/default.yml"
    prefix:   /

MesdReportDemoBundle_reports:
    resource: "@MesdReportDemoBundle/Resources/config/routing/report.yml"
    prefix:   /reports
