MesdReportDemoBundle_default:
    resource: "@MesdReportDemoBundle/Resources/config/routing/default.yml"
    prefix:   /

MesdReportDemoBundle_reports:
    resource: "@MesdReportDemoBundle/Resources/config/routing/report.yml"
    prefix:   /reports

MesdReportDemoBundle_history:
    resource: "@MesdReportDemoBundle/Resources/config/routing/history.yml"
    prefix:   /history
