parameters:
    mesd_report_options_handler_class: Mesd\ReportDemoBundle\Services\ReportFormOptionsHandler

services:
    mesd_report_demo.handler.report_options:
        class: %mesd_report_options_handler_class%
        arguments: [  ]
